### ISSUE TITLE
Save Output only logs sometimes on some hosts - Maybe not at all anymore

### ISSUE THREAD

**Issue by tmay94** [Eugeny/tabby-save-output#17]
I believe this started this week. I am unable to get hosts to log with the "Save Output" plugin. It might have to do with updating to v1.0.138. We were previously on 1.0.137. 
Let me know if there are some logs I can get or where to review any issues that are happening with this plugin and the application.

Thanks

**Comment by tmay94** [comment]
Hello,
A follow up.
It is even weirder now because multiple people have the directory set correctly, but the files don't get created at all.

**Comment by Eugeny** [comment]
Fixed in v3.1.0
